### PR TITLE
Prevent CJS output from transforming import --> require

### LINKED ISSUE #197: Cannot attach debugger to Vitest when using this preset
When using Vitest, you can pass `--inspect-brk --no-file-parallelism` to enable support for attaching a Node.js step debugger.

Unfortunately, this appears to require CJS support, which `zimmerframe` does not have, and of course, zimmerframe is a dependency of this preset.

```
FAIL  select-popover-positioning/select-popover-positioning.test.tsx [ select-popover-positioning/select-popover-positioning.test.tsx ]
Error: No "exports" main defined in /path/to/repo/node_modules/.bun/@preact+preset-vite@2.10.5+6b615289acb38f62/node_modules/zimmerframe/package.json
  Plugin: preact:transform-hook-names
  File: /path/to/repo/select-popover-positioning/select-popover-positioning.test.tsx
```

Four options I can see:
- Ask me to report this to zimmerframe
- Replace zimmerframe with your own CJS-compatible fork
- Vendor zimmerframe into this preset
- Wait for Vitest to support step-debugging when using ESM-only plugins (I assume this isn't Vitest's fault, but it surfaces there nonetheless)

Alternatively, let downstream users (me) patch zimmerframe with `pnpm patch` and accept the fact that those who need a step debugger will be required to do this.

Thanks for your time!

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Resolves #197 

The buildstep transforms import --> require for the CJS build

### CODE REVIEW

**Comment by rschristian** [comment]
Is this solvable by bumping out `typescript` version? I'd really prefer to avoid `new Function`, sets off scanners like crazy

**Comment by JoviDeCroock** [comment]
No that doesn't work, that was my first try as well 😅

File: src/transform-hook-names.ts [hunk 1]
```diff
@@ -51,7 +58,7 @@ export function transformHookNamesPlugin({
 
 			const s = new MagicString(code);
```
Comment (rschristian) [inline src/transform-hook-names.ts:59]: RIP, annoying. Wonder why it's transforming, that should be totally valid in CJS.

Edit: Approved from my phone, guess I accidentally attached the comment here. Didn't intend to comment on this particular line!

**Review by rschristian — APPROVED** [review]
